---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cwtestb2/deploy
    - export REPOPATH=/home/cwtestb2/repositories/express_server_mySql
    - /bin/rm -Rf ${DEPLOYPATH}_old
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    - /bin/cp -R ${REPOPATH}/bin ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/db ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/dist ${DEPLOYPATH}
    # - /bin/cp -R ${REPOPATH}/localDb ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/localDb ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/node_modules ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/public ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/routes ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/views ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/app.js ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/package-lock.json ${DEPLOYPATH}
    - /bin/cp -R ${REPOPATH}/package.json ${DEPLOYPATH}